---
all:
  hosts:
    sonarqube:
      ansible_connection: ssh
      ansible_ssh_user: centos
      ansible_host: 158.160.100.234
      ansible_private_key_file: ~/.ssh/id_rsa
    nexus:
      ansible_connection: ssh
      ansible_ssh_user: centos
      ansible_host: 158.160.127.133
      ansible_private_key_file: ~/.ssh/id_rsa
  children:
    postgres:
      hosts:
        sonarqube:
  vars:
    ansible_connection_type: paramiko
    ansible_user: centos
