##Предварительно выполнить на Linux хосте команду: sudo sysctl -w vm.max_map_count=262144

version: '3.8'
services:

  es-hot:
    image: elasticsearch:${VERSION}
    container_name: es-hot
    hostname: es-hot
    environment:
      - node.name=es-hot
      - cluster.name=${CLUSTER_NAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD} # default user for elastic is elastic
      - discovery.seed_hosts=es-hot,es-warm
      - cluster.initial_master_nodes=es-hot,es-warm
      - node.roles=master,data_content,data_hot  
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "http.host=0.0.0.0"
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true  # to switch off swapping on disk
    volumes:
      - es-hot:/usr/share/elasticsearch/data:Z
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200
    networks:
      elk:
        ipv4_address: 10.10.10.11
    depends_on:
      - es-warm

  es-warm:
    image: elasticsearch:${VERSION}
    container_name: es-warm
    hostname: es-warm
    environment:
      - node.name=es-warm
      - cluster.name=${CLUSTER_NAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD} # default user for elastic is elastic
      - discovery.seed_hosts=es-hot,es-warm
      - cluster.initial_master_nodes=es-hot,es-warm
      - node.roles=master,data_warm
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - "http.host=0.0.0.0"
      - bootstrap.memory_lock=true  # to switch off swapping on disk
    volumes:
      - es-warm:/usr/share/elasticsearch/data:Z
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      elk:
        ipv4_address: 10.10.10.12

  kibana:
    image: kibana:${VERSION}
    container_name: kibana
    hostname: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es-hot:9200
      ELASTICSEARCH_HOSTS: '["http://es-hot:9200","http://es-warm:9200"]'
    networks:
      elk:
        ipv4_address: 10.10.10.10
    depends_on:
      - es-hot
      - es-warm

  logstash:
    image: logstash:${VERSION}
    container_name: logstash
    hostname: logstash
    environment:
      - "LS_JAVA_OPTS=-Xms256m -Xmx256m"
      - ELASTICSEARCH_HOSTS=http://es-hot:9200 
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - 5046:5046
      - 5044:5044
    volumes:
      - logstash:/usr/share/logstash/data
      - ./configs/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:Z
      - ./configs/logstash.yml:/opt/logstash/config/logstash.yml:Z
    networks:
      elk:
        ipv4_address: 10.10.10.21
    depends_on:
      - es-hot
      - es-warm

  filebeat:
    image: elastic/filebeat:${VERSION}
    container_name: filebeat
    hostname: filebeat
    privileged: true
    user: root
    command: filebeat -e -strict.perms=false
    volumes:
      - filebeat:/usr/share/filebeat/data
      - ./configs/filebeat.yml:/usr/share/filebeat/filebeat.yml:Z
      - /var/lib/docker:/var/lib/docker:Z
      - /var/run/docker.sock:/var/run/docker.sock:Z
    depends_on:
      - logstash
    networks:
      elk:
        ipv4_address: 10.10.10.22

  some_application:
    image: library/python:3.9-alpine
    container_name: some_app
    volumes:
      - ./python/:/opt/:Z
    entrypoint: python3 /opt/run.py

volumes:
  es-hot:
    driver: local
  es-warm:
    driver: local
  filebeat:
    driver: local
  logstash:
    driver: local

networks:
  elk:
    ipam:
      driver: default
      config:
      - subnet: 10.10.10.0/24
