---
all:
  hosts:
    sonarqube:
      ansible_connection: ssh
      ansible_ssh_user: centos
      ansible_host: 130.193.37.99
      ansible_private_key_file: ~/.ssh/id_rsa
    nexus:
      ansible_connection: ssh
      ansible_ssh_user: centos
      ansible_host: 84.201.158.82
      ansible_private_key_file: ~/.ssh/id_rsa
  children:
    postgres:
      hosts:
        sonarqube:
    sonarqube:
      hosts:
        sonarqube:
    nexus:
      hosts:
        nexus:
  vars:
    ansible_connection_type: paramiko
    ansible_user: centos
