---
all:
  hosts:
    jenkins-master:
      ansible_connection: ssh
      ansible_ssh_user: centos
      ansible_host: 84.201.175.49
      ansible_private_key_file: ~/.ssh/id_rsa
    jenkins-agent:
      ansible_connection: ssh
      ansible_ssh_user: centos
      ansible_host: 178.154.225.247
      ansible_private_key_file: ~/.ssh/id_rsa
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master:
        jenkins_agents:
          hosts:
              jenkins-agent:
  vars:
    ansible_connection_type: paramiko
    ansible_user: centos
