---
all:
  hosts:
    jenkins-master:
      ansible_connection: ssh
      ansible_ssh_user: cloud-user
      ansible_host: 84.201.158.1
      ansible_private_key_file: ~/.ssh/id_rsa
    jenkins-agent:
      ansible_connection: ssh
      ansible_ssh_user: cloud-user
      ansible_host: 51.250.10.146
      ansible_private_key_file: ~/.ssh/id_rsa
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master:
        jenkins_agents:
          hosts:
              jenkins-agent:
  vars:
    ansible_connection_type: paramiko
    ansible_user: cloud-user
