---
all:
  hosts:
    jenkins-master:
      ansible_connection: ssh
      ansible_ssh_user: cloud-user
      ansible_host: 84.252.129.167
      ansible_private_key_file: ~/.ssh/id_rsa
    jenkins-agent:
      ansible_connection: ssh
      ansible_ssh_user: cloud-user
      ansible_host: 158.160.62.97
      ansible_private_key_file: ~/.ssh/id_rsa
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master:
        jenkins_agents:
          hosts:
              jenkins-agent:
  vars:
    ansible_connection_type: paramiko
    ansible_user: cloud-user
