---
all:
  hosts:
    jenkins-master:
      ansible_connection: ssh
      ansible_ssh_user: ubuntu
      ansible_host: 178.154.204.118
      ansible_private_key_file: ~/.ssh/id_rsa
    jenkins-agent:
      ansible_connection: ssh
      ansible_ssh_user: ubuntu
      ansible_host: 178.154.207.17
      ansible_private_key_file: ~/.ssh/id_rsa
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master:
        jenkins_agents:
          hosts:
              jenkins-agent:
  vars:
    ansible_connection_type: paramiko
    ansible_user: ubuntu
