---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_connection: ssh
      ansible_ssh_user: root
      ansible_host: 172.23.189.19
      ansible_private_key_file: ~/.ssh/id_ed25519

vector:
  hosts:
    vector-01:
      ansible_connection: ssh
      ansible_ssh_user: root
      ansible_host: 172.23.191.3
      ansible_private_key_file: ~/.ssh/id_ed25519
